CREATE TABLE `__new_oauth_client` (
	`id` text PRIMARY KEY,
	`client_id` text NOT NULL UNIQUE,
	`client_secret` text,
	`name` text,
	`uri` text,
	`icon` text,
	`contacts` text,
	`tos` text,
	`policy` text,
	`software_id` text,
	`software_version` text,
	`software_statement` text,
	`redirect_uris` text NOT NULL,
	`post_logout_redirect_uris` text,
	`token_endpoint_auth_method` text,
	`grant_types` text,
	`response_types` text,
	`scopes` text,
	`type` text,
	`public` integer,
	`disabled` integer DEFAULT false,
	`skip_consent` integer DEFAULT false,
	`enable_end_session` integer,
	`subject_type` text,
	`require_pkce` integer,
	`user_id` text,
	`reference_id` text,
	`metadata` text,
	`created_at` integer,
	`updated_at` integer,
	CONSTRAINT `fk_oauth_client_user_id_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON DELETE CASCADE
);
--> statement-breakpoint
INSERT INTO `__new_oauth_client`(
	`id`,
	`client_id`,
	`client_secret`,
	`name`,
	`uri`,
	`icon`,
	`contacts`,
	`tos`,
	`policy`,
	`software_id`,
	`software_version`,
	`software_statement`,
	`redirect_uris`,
	`post_logout_redirect_uris`,
	`token_endpoint_auth_method`,
	`grant_types`,
	`response_types`,
	`scopes`,
	`type`,
	`public`,
	`disabled`,
	`skip_consent`,
	`enable_end_session`,
	`subject_type`,
	`require_pkce`,
	`user_id`,
	`reference_id`,
	`metadata`,
	`created_at`,
	`updated_at`
)
SELECT
	`id`,
	`client_id`,
	`client_secret`,
	`name`,
	`uri`,
	`icon`,
	`contacts`,
	`tos`,
	`policy`,
	`software_id`,
	`software_version`,
	`software_statement`,
	`redirect_uris`,
	`post_logout_redirect_uris`,
	`token_endpoint_auth_method`,
	`grant_types`,
	`response_types`,
	`scopes`,
	`type`,
	`public`,
	`disabled`,
	CASE
		WHEN `user_id` IS NULL AND COALESCE(`skip_consent`, true) = true THEN false
		ELSE `skip_consent`
	END,
	`enable_end_session`,
	`subject_type`,
	`require_pkce`,
	`user_id`,
	`reference_id`,
	`metadata`,
	`created_at`,
	`updated_at`
FROM `oauth_client`;
--> statement-breakpoint
DROP TABLE `oauth_client`;
--> statement-breakpoint
ALTER TABLE `__new_oauth_client` RENAME TO `oauth_client`;
