// AuthStore Durable Object — single instance holding all provider auth data.
// Uses drizzle DO SQLite for BetterAuth tables + oauthProvider tables.
// Exposes libsqlproxy handler for external DB access (TablePlus, drizzle studio).

import { DurableObject } from 'cloudflare:workers'
import * as durable from 'drizzle-orm/durable-sqlite'
import * as migrator from 'drizzle-orm/durable-sqlite/migrator'
// @ts-expect-error — migrations.js is generated by drizzle-kit
import migrations from '../../db/drizzle-provider/migrations.js'
import * as schema from 'db/src/provider-schema.ts'
import { createLibsqlHandler, durableObjectExecutor } from 'libsqlproxy'

export class AuthStore extends DurableObject<Env> {
  db: durable.DrizzleSqliteDODatabase<typeof schema, typeof schema.relations>

  constructor(ctx: DurableObjectState, env: Env) {
    super(ctx, env)
    this.db = durable.drizzle(ctx.storage, { schema, relations: schema.relations })
    ctx.blockConcurrencyWhile(async () => {
      await migrator.migrate(this.db, migrations)
    })
  }

  // libsqlproxy handler for external DB access via Hrana v2
  async hranaHandler(request: Request): Promise<Response> {
    const handler = createLibsqlHandler(durableObjectExecutor(this.ctx.storage))
    return handler(request)
  }
}
