// AuthStore Durable Object — thin SQL proxy.
// Owns the SQLite database and migrations. Exposes a single executeSql()
// RPC method so the worker can run queries via drizzle-orm/sqlite-proxy.
// All business logic (auth, BetterAuth, well-known endpoints) lives in the
// worker, not here. Mirrors the app's SecretsStore pattern exactly.

import { DurableObject } from 'cloudflare:workers'
import * as durable from 'drizzle-orm/durable-sqlite'
import * as migrator from 'drizzle-orm/durable-sqlite/migrator'
// @ts-expect-error — migrations.js is generated by drizzle-kit
import migrations from '../drizzle/migrations.js'
import * as schema from './schema.ts'

export class AuthStore extends DurableObject<Env> {
  db: durable.DrizzleSqliteDODatabase<typeof schema, typeof schema.relations>

  constructor(ctx: DurableObjectState, env: Env) {
    super(ctx, env)
    this.db = durable.drizzle(ctx.storage, { schema, relations: schema.relations })
    void ctx.blockConcurrencyWhile(async () => {
      await migrator.migrate(this.db, migrations)
    })
  }

  // RPC: execute a SQL query on the DO's SQLite database.
  // Called by the worker's drizzle-orm/sqlite-proxy callback.
  // method is 'all' | 'get' | 'run' | 'values'
  async executeSql({ sql, params, method }: { sql: string; params: SqlStorageValue[]; method: string }) {
    const stmt = this.ctx.storage.sql.exec(sql, ...params)
    const columnNames = stmt.columnNames
    const rawRows = stmt.toArray()

    if (method === 'get') {
      const row = rawRows[0]
      if (!row) return { rows: null }
      const record: Record<string, SqlStorageValue> = row
      return { rows: columnNames.map((col) => record[col]) }
    }

    // For 'all', 'values', 'run' — return array of row arrays
    const rows = rawRows.map((row) => {
      const record: Record<string, SqlStorageValue> = row
      return columnNames.map((col) => record[col])
    })
    return { rows }
  }
}
