// SecretsStore Durable Object — single instance per self-hosted deployment.
// Holds BetterAuth user/session data + encrypted secrets via drizzle DO SQLite.
// Exposes RPC methods — no fetch() override.

import { DurableObject } from 'cloudflare:workers'
import * as durable from 'drizzle-orm/durable-sqlite'
import * as migrator from 'drizzle-orm/durable-sqlite/migrator'
// @ts-expect-error — migrations.js is generated by drizzle-kit
import migrations from '../../db/drizzle-app/migrations.js'
import * as schema from 'db/src/app-schema.ts'
import { createAuth } from './auth.ts'
import { registerWithProvider } from './setup.ts'

export class SecretsStore extends DurableObject<Env> {
  db: durable.DrizzleSqliteDODatabase<typeof schema, typeof schema.relations>

  constructor(ctx: DurableObjectState, env: Env) {
    super(ctx, env)
    this.db = durable.drizzle(ctx.storage, { schema, relations: schema.relations })
    ctx.blockConcurrencyWhile(async () => {
      await migrator.migrate(this.db, migrations)
    })
  }

  // RPC: handle BetterAuth /api/auth/* requests
  async authHandler(request: Request): Promise<Response> {
    const auth = createAuth({ db: this.db, env: this.env })
    return auth.handler(request)
  }

  // RPC: register with the middleman provider (called once at first deploy)
  async setup({ appUrl }: { appUrl: string }): Promise<{ clientId: string }> {
    return registerWithProvider({ db: this.db, env: this.env, appUrl })
  }
}
