// SecretsStore Durable Object — single instance per self-hosted deployment.
// Holds BetterAuth user/session data + encrypted secrets via drizzle DO SQLite.
// Exposes RPC methods — no fetch() override.
//
// BetterAuth config:
// - genericOAuth plugin: authenticates via the sigillo middleman provider
// - Public PKCE client: no client_secret, security via PKCE
// - Client ID from OAUTH_CLIENT_ID env var (set via register-client script)
//
// Crypto:
// - AES-256-GCM encryption for secrets via Web Crypto API

import { DurableObject } from 'cloudflare:workers'
import * as orm from 'drizzle-orm'
import * as durable from 'drizzle-orm/durable-sqlite'
import * as migrator from 'drizzle-orm/durable-sqlite/migrator'
// @ts-expect-error — migrations.js is generated by drizzle-kit
import migrations from '../../db/drizzle-app/migrations.js'
import * as schema from 'db/src/app-schema.ts'
import { betterAuth } from 'better-auth'
import { genericOAuth, deviceAuthorization } from 'better-auth/plugins'
import { drizzleAdapter } from 'better-auth/adapters/drizzle'

export class SecretsStore extends DurableObject<Env> {
  db: durable.DrizzleSqliteDODatabase<typeof schema, typeof schema.relations>

  constructor(ctx: DurableObjectState, env: Env) {
    super(ctx, env)
    this.db = durable.drizzle(ctx.storage, { schema, relations: schema.relations })
    ctx.blockConcurrencyWhile(async () => {
      await migrator.migrate(this.db, migrations)
    })
  }

  // ── Auth ──────────────────────────────────────────────────────

  // Build the BetterAuth instance. Client ID comes from OAUTH_CLIENT_ID
  // env var, set via the register-client script before first deploy.
  private getAuth() {
    return betterAuth({
      secret: this.env.BETTER_AUTH_SECRET,
      database: drizzleAdapter(this.db, { provider: 'sqlite' }),
      plugins: [
        genericOAuth({
          config: [
            {
              providerId: 'sigillo',
              clientId: this.env.OAUTH_CLIENT_ID,
              // Public client — no clientSecret. PKCE provides security.
              clientSecret: '',
              discoveryUrl: `${this.env.PROVIDER_URL}/.well-known/openid-configuration`,
              scopes: ['openid', 'email', 'profile'],
              pkce: true,
            },
          ],
        }),
        // RFC 8628 device flow — CLI/agents call /api/auth/device/code,
        // user enters code at /device page and signs in via provider
        deviceAuthorization({
          verificationUri: '/device',
        }),
      ],
    })
  }

  // RPC: handle BetterAuth /api/auth/* requests
  async authHandler(request: Request): Promise<Response> {
    const auth = this.getAuth()
    return auth.handler(request)
  }

  // RPC: resolve the authenticated user from request headers (session cookie).
  // Returns { userId } or null if not authenticated.
  async getSession(request: Request): Promise<{ userId: string; user: { id: string; name: string; email: string } } | null> {
    const auth = this.getAuth()
    const session = await auth.api.getSession({ headers: request.headers })
    if (!session) return null
    return { userId: session.user.id, user: { id: session.user.id, name: session.user.name, email: session.user.email } }
  }

  // ── Org CRUD ───────────────────────────────────────────────────

  async createOrg({ name, userId }: { name: string; userId: string }) {
    const [org] = this.db.insert(schema.org).values({ name })
      .returning({ id: schema.org.id, name: schema.org.name }).all()
    // Add creator as admin — ensure user exists first
    const existingUser = this.db.query.user.findFirst({ where: { id: userId } }).sync()
    if (existingUser) {
      this.db.insert(schema.orgMember).values({ orgId: org!.id, userId, role: 'admin' }).run()
    } else {
      // Create a default system user for unauthenticated setup
      this.db.insert(schema.user).values({ id: userId, name: 'System', email: `${userId}@sigillo.local` }).onConflictDoNothing().run()
      this.db.insert(schema.orgMember).values({ orgId: org!.id, userId, role: 'admin' }).run()
    }
    return org!
  }

  async listUserOrgs({ userId }: { userId: string }) {
    // Get all orgs the user is a member of
    const members = this.db.query.orgMember.findMany({
      where: { userId },
      with: { org: true },
    }).sync()
    return members.filter((m) => m.org != null).map((m) => ({
      id: m.org!.id!,
      name: m.org!.name!,
      role: m.role,
      createdAt: m.org!.createdAt!,
      updatedAt: m.org!.updatedAt!,
    }))
  }

  // ── Project CRUD ───────────────────────────────────────────────
  // Creating a project also creates the default environments (development, preview, production)

  async createProject({ name, orgId }: { name: string; orgId: string }) {
    const [proj] = this.db.insert(schema.project).values({ name, orgId })
      .returning({ id: schema.project.id, name: schema.project.name }).all()
    // Create default environments
    for (const env of schema.DEFAULT_ENVIRONMENTS) {
      this.db.insert(schema.environment).values({ projectId: proj!.id, name: env.name, slug: env.slug }).run()
    }
    return proj!
  }

  async listProjects({ orgId }: { orgId: string }) {
    return this.db.query.project.findMany({
      where: { orgId },
      with: { environments: true },
      orderBy: { createdAt: 'desc' },
    }).sync()
  }

  async deleteProject({ id }: { id: string }) {
    const [deleted] = this.db.delete(schema.project)
      .where(orm.eq(schema.project.id, id))
      .returning({ id: schema.project.id }).all()
    return deleted ?? null
  }

  // ── Environment CRUD ──────────────────────────────────────────

  async listEnvironments({ projectId }: { projectId: string }) {
    return this.db.query.environment.findMany({
      where: { projectId },
      orderBy: { createdAt: 'asc' },
    }).sync()
  }

  async createEnvironment({ projectId, name, slug }: { projectId: string; name: string; slug: string }) {
    const [row] = this.db.insert(schema.environment).values({ projectId, name, slug })
      .returning({ id: schema.environment.id, name: schema.environment.name, slug: schema.environment.slug }).all()
    return row!
  }

  async deleteEnvironment({ id }: { id: string }) {
    const [deleted] = this.db.delete(schema.environment)
      .where(orm.eq(schema.environment.id, id))
      .returning({ id: schema.environment.id }).all()
    return deleted ?? null
  }

  // ── Secret CRUD (scoped to environment) ───────────────────────

  async listSecrets({ environmentId }: { environmentId: string }) {
    const rows = this.db.query.secret.findMany({
      where: { environmentId },
      with: { creator: { columns: { id: true, name: true } } },
      orderBy: { createdAt: 'desc' },
    }).sync()
    // Return names + ids + timestamps, never encrypted values
    return rows.map((r) => ({ id: r.id, name: r.name, createdAt: r.createdAt, updatedAt: r.updatedAt, createdBy: r.creator }))
  }

  async listSecretsWithValues({ environmentId }: { environmentId: string }) {
    const rows = this.db.query.secret.findMany({
      where: { environmentId },
      with: { creator: { columns: { id: true, name: true } } },
      orderBy: { createdAt: 'desc' },
    }).sync()
    const secrets = await Promise.all(rows.map(async (r) => {
      const value = await this.decrypt({ encrypted: r.valueEncrypted, iv: r.iv })
      return { id: r.id, name: r.name, value, createdAt: r.createdAt, updatedAt: r.updatedAt, createdBy: r.creator }
    }))
    return secrets
  }

  async updateSecret({ id, name, value }: { id: string; name?: string; value?: string }) {
    if (name !== undefined) {
      this.db.update(schema.secret)
        .set({ name, updatedAt: Date.now() })
        .where(orm.eq(schema.secret.id, id))
        .run()
    }
    if (value !== undefined) {
      const { encrypted, iv } = await this.encrypt({ plaintext: value })
      this.db.update(schema.secret)
        .set({ valueEncrypted: encrypted, iv, updatedAt: Date.now() })
        .where(orm.eq(schema.secret.id, id))
        .run()
    }
    return { id }
  }

  async createSecret({ environmentId, name, value, createdBy }: { environmentId: string; name: string; value: string; createdBy: string }) {
    const { encrypted, iv } = await this.encrypt({ plaintext: value })
    const [row] = this.db.insert(schema.secret).values({
      environmentId,
      name,
      valueEncrypted: encrypted,
      iv,
      createdBy,
    }).returning({ id: schema.secret.id, name: schema.secret.name }).all()
    return row!
  }

  async getSecret({ id }: { id: string }) {
    const row = this.db.query.secret.findFirst({
      where: { id },
    }).sync()
    if (!row) return null
    const value = await this.decrypt({ encrypted: row.valueEncrypted, iv: row.iv })
    return { id: row.id, name: row.name, value, environmentId: row.environmentId, createdAt: row.createdAt, updatedAt: row.updatedAt }
  }

  async deleteSecret({ id }: { id: string }) {
    const [deleted] = this.db.delete(schema.secret)
      .where(orm.eq(schema.secret.id, id))
      .returning({ id: schema.secret.id })
      .all()
    return deleted ?? null
  }

  // ── Crypto ────────────────────────────────────────────────────

  async encrypt({ plaintext }: { plaintext: string }): Promise<{ encrypted: string; iv: string }> {
    const key = await getEncryptionKey(this.env.ENCRYPTION_KEY)
    const iv = crypto.getRandomValues(new Uint8Array(12))
    const encoded = new TextEncoder().encode(plaintext)
    const ciphertext = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, key, encoded)
    return {
      encrypted: btoa(String.fromCharCode(...new Uint8Array(ciphertext))),
      iv: btoa(String.fromCharCode(...iv)),
    }
  }

  async decrypt({ encrypted, iv }: { encrypted: string; iv: string }): Promise<string> {
    const key = await getEncryptionKey(this.env.ENCRYPTION_KEY)
    const ivBytes = Uint8Array.from(atob(iv), (c) => c.charCodeAt(0))
    const ciphertext = Uint8Array.from(atob(encrypted), (c) => c.charCodeAt(0))
    const plaintext = await crypto.subtle.decrypt({ name: 'AES-GCM', iv: ivBytes }, key, ciphertext)
    return new TextDecoder().decode(plaintext)
  }
}

async function getEncryptionKey(base64Key: string): Promise<CryptoKey> {
  const raw = Uint8Array.from(atob(base64Key), (c) => c.charCodeAt(0))
  return crypto.subtle.importKey('raw', raw, { name: 'AES-GCM' }, false, ['encrypt', 'decrypt'])
}
