// SecretsStore Durable Object — single instance per self-hosted deployment.
// Holds BetterAuth user/session data + encrypted secrets via drizzle DO SQLite.
// Exposes RPC methods — no fetch() override.
//
// BetterAuth config:
// - genericOAuth plugin: authenticates via the sigillo middleman provider
// - Public PKCE client: no client_secret, security via PKCE
// - Client ID read from config table (populated by setup RPC at first deploy)
//
// Crypto:
// - AES-256-GCM encryption for secrets via Web Crypto API

import { DurableObject } from 'cloudflare:workers'
import { eq } from 'drizzle-orm'
import * as durable from 'drizzle-orm/durable-sqlite'
import * as migrator from 'drizzle-orm/durable-sqlite/migrator'
// @ts-expect-error — migrations.js is generated by drizzle-kit
import migrations from '../../db/drizzle-app/migrations.js'
import * as schema from 'db/src/app-schema.ts'
import { betterAuth } from 'better-auth'
import { genericOAuth } from 'better-auth/plugins'
import { drizzleAdapter } from 'better-auth/adapters/drizzle'

export class SecretsStore extends DurableObject<Env> {
  db: durable.DrizzleSqliteDODatabase<typeof schema, typeof schema.relations>

  constructor(ctx: DurableObjectState, env: Env) {
    super(ctx, env)
    this.db = durable.drizzle(ctx.storage, { schema, relations: schema.relations })
    ctx.blockConcurrencyWhile(async () => {
      await migrator.migrate(this.db, migrations)
    })
  }

  // ── Auth ──────────────────────────────────────────────────────

  // RPC: handle BetterAuth /api/auth/* requests
  async authHandler(request: Request): Promise<Response> {
    const row = this.db.select().from(schema.config).where(eq(schema.config.key, 'middleman_client_id')).get()
    if (!row) {
      throw new Error('OAuth client_id not found in config table. Run /api/setup first.')
    }

    const auth = betterAuth({
      secret: this.env.BETTER_AUTH_SECRET,
      database: drizzleAdapter(this.db, { provider: 'sqlite' }),
      plugins: [
        genericOAuth({
          config: [
            {
              providerId: 'sigillo',
              clientId: row.value,
              // Public client — no clientSecret. PKCE provides security.
              clientSecret: '',
              discoveryUrl: `${this.env.PROVIDER_URL}/.well-known/openid-configuration`,
              scopes: ['openid', 'email', 'profile'],
              pkce: true,
            },
          ],
        }),
      ],
    })
    return auth.handler(request)
  }

  // ── Setup ─────────────────────────────────────────────────────

  // RPC: register with the middleman provider (called once at first deploy).
  // Registers as a PUBLIC client (token_endpoint_auth_method: "none").
  // BetterAuth's oauthProvider only allows unauthenticated registration
  // for public clients. Security comes from PKCE, not a client_secret.
  async setup({ appUrl }: { appUrl: string }): Promise<{ clientId: string }> {
    // Check if already registered
    const existing = this.db.select().from(schema.config).where(eq(schema.config.key, 'middleman_client_id')).get()
    if (existing) {
      return { clientId: existing.value }
    }

    const callbackUrl = `${appUrl}/api/auth/oauth2/callback/sigillo`

    const response = await fetch(`${this.env.PROVIDER_URL}/api/auth/oauth2/register`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        client_name: `Sigillo Self-Hosted (${appUrl})`,
        redirect_uris: [callbackUrl],
        grant_types: ['authorization_code', 'refresh_token'],
        response_types: ['code'],
        scope: 'openid email profile',
        token_endpoint_auth_method: 'none',
      }),
    })

    if (!response.ok) {
      const body = await response.text()
      throw new Error(`Failed to register with provider: ${response.status} ${body}`)
    }

    const client = (await response.json()) as { client_id: string }

    this.db.insert(schema.config).values({ key: 'middleman_client_id', value: client.client_id }).run()

    return { clientId: client.client_id }
  }

  // ── Crypto ────────────────────────────────────────────────────

  async encrypt({ plaintext }: { plaintext: string }): Promise<{ encrypted: string; iv: string }> {
    const key = await getEncryptionKey(this.env.ENCRYPTION_KEY)
    const iv = crypto.getRandomValues(new Uint8Array(12))
    const encoded = new TextEncoder().encode(plaintext)
    const ciphertext = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, key, encoded)
    return {
      encrypted: btoa(String.fromCharCode(...new Uint8Array(ciphertext))),
      iv: btoa(String.fromCharCode(...iv)),
    }
  }

  async decrypt({ encrypted, iv }: { encrypted: string; iv: string }): Promise<string> {
    const key = await getEncryptionKey(this.env.ENCRYPTION_KEY)
    const ivBytes = Uint8Array.from(atob(iv), (c) => c.charCodeAt(0))
    const ciphertext = Uint8Array.from(atob(encrypted), (c) => c.charCodeAt(0))
    const plaintext = await crypto.subtle.decrypt({ name: 'AES-GCM', iv: ivBytes }, key, ciphertext)
    return new TextDecoder().decode(plaintext)
  }
}

async function getEncryptionKey(base64Key: string): Promise<CryptoKey> {
  const raw = Uint8Array.from(atob(base64Key), (c) => c.charCodeAt(0))
  return crypto.subtle.importKey('raw', raw, { name: 'AES-GCM' }, false, ['encrypt', 'decrypt'])
}
